name: Test secrets availability

on:
  workflow_dispatch:   # ручний запуск із вкладки Actions
  schedule:
    - cron: '15 8 * * *'   # раз на день о 08:15 UTC (можна прибрати)

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Verify that OPENAI_API_KEY is set
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ OPENAI_API_KEY is NOT set"; exit 1;
          else
            echo "✅ OPENAI_API_KEY detected (length=${#OPENAI_API_KEY})";
          fi
      - name: Verify that TELEGRAM_TOKEN is set
        run: |
          if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ]; then
            echo "❌ TELEGRAM_TOKEN is NOT set"; exit 1;
          else
            echo "✅ TELEGRAM_TOKEN detected (length=${#TELEGRAM_TOKEN})";
          fi
      - name: Verify that TELEGRAM_CHANNEL is set
        run: |
          if [ -z "${{ secrets.TELEGRAM_CHANNEL }}" ]; then
            echo "❌ TELEGRAM_CHANNEL is NOT set"; exit 1;
          else
            echo "✅ TELEGRAM_CHANNEL detected (value=${{ secrets.TELEGRAM_CHANNEL }})";
          fi
      - name: All secrets check summary
        run: |
          echo "🎉 All required secrets are properly configured!"
          echo "Ready to run the main news parser workflow."
